import React from 'react'
import Card from '../components/Card'
import {  FaPencilAlt, FaRuler  } from "react-icons/fa";
import { MdSettingsSuggest, MdDownloadForOffline } from "react-icons/md";
import { Link } from 'react-router-dom';
import colorPallete from '../context/colors';

function How() {
  const theme=colorPallete()
  return (
    <section className='max-w-7xl mx-auto'>
 <section style={{ backgroundColor: theme.bg2}}  className='shadow-lg my-4 p-8 lg:max-w-7xl lg:mx-auto mx-8 rounded-md'>
    <h1 style={{ color: theme.color}}  className='text-center text-2xl font-bold text-white p-6'>How it Works </h1>
    
    <div className='flex flex-wrap lg:grid grid-cols-2 lg:my-8 '>
          <Card
        icon={<FaRuler color="white" fontSize="32"/>}
        title="Choose Your Genre"
        description="Select from a wide range of genres or create a custom blend"
       
    />
     <Card
        icon={<FaPencilAlt color="white" fontSize="32"/>}
        title="Provide Key details"
        description="Input main characters, plot points, or themes to guide the AI"
        
    />
    </div>
       
    
    <div className='flex flex-wrap lg:grid grid-cols-2  justify-around lg:my-16 '>
         <Card
        icon={<MdSettingsSuggest color="white" fontSize="32"/>}
        title="AI Generation"
        description="Our advanced AI create your book based on your inputs"
       
    />
     <Card
        icon={<MdDownloadForOffline color="white" fontSize="32"/>}
        title="Review and Download"
        description="Review your generated book and download in your preferred format"
       
    />
    </div>
    </section>    
    <h1 style={{ color: theme.color}}  className='text-center lg:text-2xl text-xl font-bold'>Sample Books Generated by BookAI</h1> 
    <h2 style={{ color: theme.color}}  className='text-center lg:text-xl text-sm my-8 font-bold'>Explore some of the captivationg books created using our AI technology</h2>  
    <section className='flex flex-wrap lg:grid grid-cols-3 mx-6'>
       <div style={{ backgroundColor: theme.bg2}}  className='py-2 px-8 shadow-lg  items-center justify-center mx-4 
       my-4 rounded-md transform hover:scale-105 transition duration-300 ease-in-out'>
        <img src="paradox.png" alt="paradox" className='w-48 h-72 mx-auto' />
        <div className='my-4 '>
            <h1 style={{ color: theme.color}}  className='font-extrabold text-2xl text-center'>Science Fiction</h1>
            <p  style={{ color: theme.color2}} className='text-stone-400 text-lg text-center text-wrap italic'>
            "As Dr. Elara stepped through the shimmering portal, she knew there was no turning back. The fate of two universes now rested in her hands..."
            </p>
            <Link to="/" >
            <h1 className='text-purple-800 text-center hover:text-white font-bold text-xl my-6'>Read More</h1></Link>
        </div>
       </div>
       <div style={{ backgroundColor: theme.bg2}} className='py-2 shadow-lg px-8 items-center
       transform hover:scale-105 transition duration-300 ease-in-out mx-4 my-4'>
        <img src="paradox.png" alt="paradox" className='w-48 h-72 mx-auto' />
        <div className='my-4'>
            <h1 style={{ color: theme.color}}  className='font-extrabold text-2xl text-center'>Mystery</h1>
            <p style={{ color: theme.color2}} className=' text-lg text-center text-wrap italic'>
            "The old lighthouse stood silent, its beacon long extinguished. But on foggy nights, 
            some swore they could still see its ghostly light..."
            </p>
            <Link to="/" >
            <h1 className='text-purple-800 text-center hover:text-white font-bold text-xl my-6'>Read More</h1></Link>
        </div>
       </div>
       <div style={{ backgroundColor: theme.bg2}} className='py-2 shadow-lg lg:px-8
       transform hover:scale-105 transition duration-300 ease-in-out items-center mx-4 my-4'>
        <img src="paradox.png" alt="paradox" className='w-48 h-72 mx-auto' />
        <div className='my-4'>
            <h1 style={{ color: theme.color}}  className='font-extrabold text-center text-2xl'>Fantasy</h1>
            <p style={{ color: theme.color2}} className=' text-lg text-center text-wrap italic'>
            "The ancient prophecy spoke of a child born with starlight in their eyes. 
            As the comet blazed overhead, the kingdom held its breath..."
            </p>
            <Link to="/" >
            <h1 className='text-purple-800 text-center hover:text-white font-bold text-xl my-6'>Read More</h1></Link>
        </div>
       </div>
       
    </section> 
    <div style={{backgroundColor:theme.bg5}}  className=' book2 py-8 px-6  relative rounded-md w-full h-fit my-16   mx-auto '>
         <div className="w-100 h-100 ">
         <img src="book2.png" alt="book2" className='rounded-lg transition-transform transform hover:scale-105' /></div>
         <div className='paradox top-6 absolute bg-slate-300 py-2 pl-10 pr-2 rounded-lg transition-transform transform hover:scale-105'>
    <img src="paradox.png" alt="paradox" className='w-24 rounded-lg h-32' />
</div>
<div className='paradox absolute right-4 flex bottom-4 px-7 py-3 rounded-lg items-center'>
  <button className='bg-sky-500 w-8 h-8 rounded-full'></button>
  <h1 className='text-white font-bold text-xl bottom-16 ml-2'>Chapter Complete</h1>
</div>

      </div>
    </section>
   
  )
}

export default How
