import React from 'react'
import Card from '../components/Card'
import {  FaPencilAlt, FaRuler  } from "react-icons/fa";
import { MdSettingsSuggest, MdDownloadForOffline } from "react-icons/md";
import { Link } from 'react-router-dom';


function How() {
  return (
    <section className='max-w-7xl mx-auto'>
 <section className='how my-4 p-8 max-w-7xl mx-auto'>
    <h1 className='text-center text-2xl font-bold text-white p-6'>How it Works </h1>
    
    <div className='flex flex-wrap justify-around my-8 '>
          <Card
        icon={<FaRuler color="white" fontSize="32"/>}
        title="Choose Your Genre"
        description="Select from a wide range of genres or create a custom blend"
        containerStyles="flex items-center mx-4 lg:my-0 my-8"
         iconStyles="bg-sky-500 w-16 h-16 rounded-full flex items-center justify-center mx-6"
    />
     <Card
        icon={<FaPencilAlt color="white" fontSize="32"/>}
        title="Provide Key details"
        description="Input main characters, plot points, or themes to guide the AI"
        containerStyles="flex items-center"
         iconStyles="bg-sky-500 w-16 h-16 rounded-full flex items-center justify-center mx-6"
    />
    </div>
       
    
    <div className='flex flex-wrap justify-around my-16 '>
         <Card
        icon={<MdSettingsSuggest color="white" fontSize="32"/>}
        title="AI Generation"
        description="Our advanced AI create your book based on your inputs"
        containerStyles="flex items-center mx-4 lg:my-0 my-8"
         iconStyles="bg-sky-500 w-16 h-16 rounded-full flex items-center justify-center mx-6"
    />
     <Card
        icon={<MdDownloadForOffline color="white" fontSize="32"/>}
        title="Review and Download"
        description="Review your generated book and download in your preferred format"
        containerStyles="flex items-center"
         iconStyles="bg-sky-500 w-16 h-16 rounded-full flex items-center justify-center mx-6"
    />
    </div>
    </section>    
    <h1 className='text-center lg:text-2xl text-xl font-bold text-white'>Sample Books Generated by BookAI</h1> 
    <h2 className='text-center lg:text-xl text-sm my-8 font-bold text-white'>Explore some of the captivationg books created using our AI technology</h2>  
    <section className='flex flex-wrap lg:grid grid-cols-3'>
       <div className='py-2 px-8 how items-center justify-center mx-4 my-4 rounded-md'>
        <img src="paradox.png" alt="paradox" className='w-48 h-72 mx-auto' />
        <div className='my-4 '>
            <h1 className='font-extrabold text-2xl text-center text-white'>Science Fiction</h1>
            <p className='text-stone-400 text-lg text-center text-wrap italic'>
            "As Dr. Elara stepped through the shimmering portal, she knew there was no turning back. The fate of two universes now rested in her hands..."
            </p>
            <Link to="/" >
            <h1 className='text-purple-800 text-center hover:text-white font-bold text-xl my-6'>Read More</h1></Link>
        </div>
       </div>
       <div className='py-2 px-8 how items-center mx-4 my-4'>
        <img src="paradox.png" alt="paradox" className='w-48 h-72 mx-auto' />
        <div className='my-4'>
            <h1 className='font-extrabold text-2xl text-center text-white'>Mystery</h1>
            <p className='text-stone-400 text-lg text-center text-wrap italic'>
            "The old lighthouse stood silent, its beacon long extinguished. But on foggy nights, 
            some swore they could still see its ghostly light..."
            </p>
            <Link to="/" >
            <h1 className='text-purple-800 text-center hover:text-white font-bold text-xl my-6'>Read More</h1></Link>
        </div>
       </div>
       <div className='py-2 lg:px-8 how items-center mx-4 my-4'>
        <img src="paradox.png" alt="paradox" className='w-48 h-72 mx-auto' />
        <div className='my-4'>
            <h1 className='font-extrabold text-center text-2xl text-white'>Fantasy</h1>
            <p className='text-stone-400 text-lg text-center text-wrap italic'>
            "The ancient prophecy spoke of a child born with starlight in their eyes. 
            As the comet blazed overhead, the kingdom held its breath..."
            </p>
            <Link to="/" >
            <h1 className='text-purple-800 text-center hover:text-white font-bold text-xl my-6'>Read More</h1></Link>
        </div>
       </div>
    </section> 
    </section>
   
  )
}

export default How
